# Generated by Django 3.1.1 on 2020-09-04 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.IntegerField()),
                ('ibge7', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=128)),
                ('regiao', models.CharField(max_length=15)),
                ('populacao_2010', models.IntegerField()),
                ('capital', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapeamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Público'), (2, 'Não público'), (3, 'Sem informação')])),
                ('data_inicial', models.DateField()),
                ('link_do', models.URLField()),
                ('tipo_arquivo', models.IntegerField(choices=[(1, 'PDF'), (2, 'Docx')])),
                ('validacao', models.BooleanField()),
                ('navegacao', models.FloatField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.municipio')),
            ],
        ),
    ]
