# Generated by Django 3.1.1 on 2020-09-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20200909_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeamento',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapeamento',
            name='link_do',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapeamento',
            name='tipo_arquivo',
            field=models.IntegerField(blank=True, choices=[(1, 'PDF Texto'), (2, 'PDF imagem'), (3, 'DOCX'), (4, 'HTML'), (5, 'TXT'), (6, 'Outro formato')], null=True),
        ),
    ]
