# Generated by Django 3.1.1 on 2020-09-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20200910_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='validacao',
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='validacao',
            field=models.BooleanField(default=False),
        ),
    ]
