# Generated by Django 3.1.1 on 2020-09-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_auto_20200909_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mapeamento',
            name='link_do',
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='links_fontes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.fonte'),
        ),
    ]
