# Generated by Django 3.1.1 on 2020-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_auto_20200909_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapeamento',
            name='links_fontes',
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='fonte_1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='fonte_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='fonte_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='fonte_4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fonte',
        ),
    ]
