# Generated by Django 3.1.1 on 2020-09-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_auto_20200911_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='capital',
            field=models.BooleanField(default=False),
        ),
    ]
