# Generated by Django 3.1.1 on 2020-09-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20200912_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
