# Generated by Django 3.1.1 on 2020-09-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_auto_20200912_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapeamento',
            name='tipo_arquivo',
            field=models.IntegerField(blank=True, choices=[(1, 'PDF texto'), (2, 'PDF imagem'), (3, 'DOCX'), (4, 'HTML'), (5, 'TXT'), (6, 'Outro formato')], null=True),
        ),
    ]
