# Generated by Django 3.1.1 on 2020-10-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_mapeamento_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapeamento',
            name='anomalia_obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapeamento',
            name='tem_anomalia',
            field=models.BooleanField(default=False),
        ),
    ]
