# Generated by Django 3.1.1 on 2020-10-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_auto_20200930_2055'),
        ('formulario', '0008_mapeamento_observacoes'),
    ]

    operations = [
    ]
