# Generated by Django 3.1.1 on 2020-10-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_merge_20201001_2036'),
        ('formulario', '0009_auto_20201003_1733'),
    ]

    operations = [
    ]
