# Generated by Django 3.1.1 on 2020-11-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_merge_20201009_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoValidado',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('formulario.mapeamento',),
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='populacao_2010',
            new_name='populacao_2020',
        ),
    ]
