# Generated by Django 3.1.1 on 2020-11-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0011_auto_20201128_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoValidadoCapitai',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('formulario.mapeamento',),
        ),
        migrations.CreateModel(
            name='MapeamentoValidadoCemMilHabitante',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('formulario.mapeamento',),
        ),
    ]
