# Generated by Django 3.1.1 on 2020-11-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0012_mapeamentovalidadocapitai_mapeamentovalidadocemmilhabitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapeamentoCemMilhabitante',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('formulario.mapeamento',),
        ),
    ]
